updated tests for CI/CD

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -50,7 +50,7 @@ jobs:
 
       - name: Wait for WebSocket inside Docker (Timeout 30s)
         run: |
-          timeout 30 sh -c 'until nc -z 0.0.0.0 8002; do sleep 1; done' || (echo "WebSocket service failed to start!" && exit 1)
+          timeout 30 sh -c 'until nc -z web 8002; do sleep 1; done' || (echo "WebSocket service failed to start!" && exit 1)
 
       - name: Run tests
         run: |
